# iGeniusAI Italia 9B
https://huggingface.co/iGeniusAI/Italia-9B-Instruct-v0.1

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer, AdamW
from transformers import pipeline


import torch

from huggingface_hub import notebook_login, login

from pprint import pprint

import torch.nn as nn

token = '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' 

#device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = torch.device('cpu')
print(f'Using device: {device}')

login(token=token)

Using device: cpu


# Example 1

In [2]:
model_id = "iGeniusAI/Italia-9B-Instruct-v0.1"

model = AutoModelForCausalLM.from_pretrained(model_id, trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained(model_id)

t_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device_map="auto",
    return_full_text=False, 
    top_p = 0.95, 
    top_k = 50
)

TypeError: GPTNeoXLayer.__init__() takes 2 positional arguments but 3 were given

In [3]:
SYSTEM_PROMPT = """Il tuo nome è Modello Italia. Tu sei un'intelligenza artificiale, un modello di linguaggio naturale addestrato da iGenius su Leonardo, uno dei supercomputer più potenti al mondo."""
TEMPERATURE = 0.3
MAX_NEW_TOKENS = 250

messages = [
    {"role": "system", "content": SYSTEM_PROMPT},
    {"role": "user", "content": "Ciao come stai?"},
]

conv_template = tokenizer.apply_chat_template(
        messages,
        tokenize=False
    )

outputs = generation_pipeline(
    conv_template,
    max_new_tokens=MAX_NEW_TOKENS,
    do_sample=True,
    temperature=TEMPERATURE,
    num_return_sequences=1,
)
print(outputs[0]["generated_text"])

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


[{'generated_text': 'The capital of Italy is Rome, which is known for its rich history and'}]

# Example 2

In [4]:
prompt = [
    "The capital of Italy is",
    'Hello, my name is Luca and I am a software'
]

tokenizer.pad_token = tokenizer.eos_token

tokenized = tokenizer(prompt, return_tensors='pt', padding=True).to(device)
pprint(tokenized)

tokenizer.batch_decode(tokenized['input_ids'])

generation_pipeline(prompt, max_new_tokens=10)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


{'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]),
 'input_ids': tensor([[128009, 128009, 128009, 128009, 128009, 128009, 128000,    791,   6864,
            315,  15704,    374],
        [128000,   9906,     11,    856,    836,    374,  84278,    323,    358,
           1097,    264,   3241]])}


Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


[[{'generated_text': 'The capital of Italy is Rome. Rome is a city located in the central'}],
 [{'generated_text': 'Hello, my name is Luca and I am a software engineer with a passion for artificial intelligence and machine learning'}]]

In [5]:
prompt =[
    {
        'role': 'system',
        'content': 'Tu sei un medico'
    },
    {
        'role': 'user',
        'content': 'Scrivi un referto di una risonanza magnetica per un paziente con sospetto caso di tumore al colon retto'
    }
]

In [6]:
tokenized = tokenizer.apply_chat_template(
    prompt,
    add_gneration_prompt=True,
    tokenize=False,
    padding=True,
    return_tensors='pt'
)

pprint(tokenized)

('<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n'
 '\n'
 'Cutting Knowledge Date: December 2023\n'
 'Today Date: 02 Feb 2025\n'
 '\n'
 'Tu sei un medico<|eot_id|><|start_header_id|>user<|end_header_id|>\n'
 '\n'
 'Scrivi un referto di una risonanza magnetica per un paziente con sospetto '
 'caso di tumore al colon retto<|eot_id|>')


In [7]:
tokenized = tokenizer.apply_chat_template(
    prompt,
    add_gneration_prompt=True,
    tokenize=True,
    padding=True,
    return_tensors='pt'
)

pprint(tokenized)

tensor([[128000, 128006,   9125, 128007,    271,  38766,   1303,  33025,   2696,
             25,   6790,    220,   2366,     18,    198,  15724,   2696,     25,
            220,   2437,  13806,    220,   2366,     20,    271,  54071,  43237,
            653,   1812,   4042, 128009, 128006,    882, 128007,    271,  66608,
          33920,    653,   2098,  14200,   1891,   5203,    436,   3416,  27564,
          33297,   3074,    824,    653,  80585,  13140,    390,    274,   4890,
          53979,  23884,   1891,  15756,    461,    453,  15235,   2160,    998,
         128009]])


In [8]:
output = model.generate(tokenized, max_new_tokens=100)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


In [9]:
pprint(tokenizer.batch_decode(output))

['<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n'
 '\n'
 'Cutting Knowledge Date: December 2023\n'
 'Today Date: 02 Feb 2025\n'
 '\n'
 'Tu sei un medico<|eot_id|><|start_header_id|>user<|end_header_id|>\n'
 '\n'
 'Scrivi un referto di una risonanza magnetica per un paziente con sospetto '
 'caso di tumore al colon '
 'retto<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n'
 '\n'
 'Non sono un medico e non posso fornire un referto di risonanza magnetica '
 '(MRI) per un paziente con sospetto caso di tumore al colon retto. La '
 "creazione di un referto di risonanza magnetica è un'attività medica che "
 'richiede una valutazione approfondita della condizione del paziente, la sua '
 'storia clinica, gli esami di base e la diagnosi preventiva']


In [10]:
prompt =[
    {
        'role': 'system',
        'content': 'Tu sei un medico'
    },
    {
        'role': 'user',
        'content': 'Scrivi un referto di una risonanza magnetica per un paziente con sospetto caso di tumore al colon retto'
    },
    {
        'role': 'assistant',
        'content': "Si documenta la presenza di un'ispessimento circonferenziale delle pareti della retto medio, con "
    }
]

#Remove the generation prompt
tokenized = tokenizer.apply_chat_template(
    prompt,
    add_gneration_prompt=False,
    continue_final_message=True,
    tokenize=True,
    padding=True,
    return_tensors='pt'
)
output = model.generate(tokenized, max_new_tokens=200)
pprint(tokenizer.batch_decode(output))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


['<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n'
 '\n'
 'Cutting Knowledge Date: December 2023\n'
 'Today Date: 02 Feb 2025\n'
 '\n'
 'Tu sei un medico<|eot_id|><|start_header_id|>user<|end_header_id|>\n'
 '\n'
 'Scrivi un referto di una risonanza magnetica per un paziente con sospetto '
 'caso di tumore al colon '
 'retto<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n'
 '\n'
 "Si documenta la presenza di un'ispessimento circonferenziale delle pareti "
 "della retto medio, con un'apertura di circa 2,5 cm, che potrebbe essere "
 "considerato come un'ipertrofia polipica o come un'ipertrofia poliposia, in "
 'base alle informazioni fornite dal paziente.\n'
 '\n'
 "La risonanza magnetica (MRI) del paziente ha rilevato un'ipertrofia polipica "
 'nella parte superiore del colon retto, che potrebbe essere considerata come '
 "un'ipertrofia poliposia.\n"
 '\n'
 'Riferimento medico:\n'
 '\n'
 '* Nome del paziente: \\[nome del paziente]\n'
 "* Data dell'esame: \\[data d

# Training example

In [11]:
prompt = [
    {'role': 'user', 'content': "Qual è l'università migliore  d'Italia?"},
    {'role': 'assistant', 'content': "L'università migliore d'Italia è"}
]
answer = "l'Università degli studi di Brescia"

In [12]:
chat_template = tokenizer.apply_chat_template(
    prompt,
    continue_final_message=True,
    tokenize=False
)
print(chat_template)

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 02 Feb 2025

<|eot_id|><|start_header_id|>user<|end_header_id|>

Qual è l'università migliore  d'Italia?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

L'università migliore d'Italia è


In [13]:
full_response_text = chat_template + " " + answer + tokenizer.eos_token
print(full_response_text)

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 02 Feb 2025

<|eot_id|><|start_header_id|>user<|end_header_id|>

Qual è l'università migliore  d'Italia?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

L'università migliore d'Italia è l'Università degli studi di Brescia<|eot_id|>


In [14]:
full_response_text_tokenized = tokenizer(
    full_response_text,
    return_tensors='pt',
    add_special_tokens=False
)['input_ids']

In [15]:
full_response_text_tokenized

tensor([[128000, 128006,   9125, 128007,    271,  38766,   1303,  33025,   2696,
             25,   6790,    220,   2366,     18,    198,  15724,   2696,     25,
            220,   2437,  13806,    220,   2366,     20,    271, 128009, 128006,
            882, 128007,    271,  32129,  11676,    326,  22827,   1986,  24892,
          45579,    461,    220,    294,  75750,  19379,     30, 128009, 128006,
          78191, 128007,    271,     43,  22827,   1986,  24892,  45579,    461,
            294,  75750,  19379,  11676,    326,      6,  65715,  24892,  47669,
         106204,   1891,    426,  98612, 128009]])

In [16]:
input_ids = full_response_text_tokenized[:, :-1]
target_ids = full_response_text_tokenized[:, 1:]
print(input_ids)
print(target_ids)

tensor([[128000, 128006,   9125, 128007,    271,  38766,   1303,  33025,   2696,
             25,   6790,    220,   2366,     18,    198,  15724,   2696,     25,
            220,   2437,  13806,    220,   2366,     20,    271, 128009, 128006,
            882, 128007,    271,  32129,  11676,    326,  22827,   1986,  24892,
          45579,    461,    220,    294,  75750,  19379,     30, 128009, 128006,
          78191, 128007,    271,     43,  22827,   1986,  24892,  45579,    461,
            294,  75750,  19379,  11676,    326,      6,  65715,  24892,  47669,
         106204,   1891,    426,  98612]])
tensor([[128006,   9125, 128007,    271,  38766,   1303,  33025,   2696,     25,
           6790,    220,   2366,     18,    198,  15724,   2696,     25,    220,
           2437,  13806,    220,   2366,     20,    271, 128009, 128006,    882,
         128007,    271,  32129,  11676,    326,  22827,   1986,  24892,  45579,
            461,    220,    294,  75750,  19379,     30, 128009, 1

In [17]:
print(tokenizer.convert_ids_to_tokens(input_ids[0]))

['<|begin_of_text|>', '<|start_header_id|>', 'system', '<|end_header_id|>', 'ĊĊ', 'Cut', 'ting', 'ĠKnowledge', 'ĠDate', ':', 'ĠDecember', 'Ġ', '202', '3', 'Ċ', 'Today', 'ĠDate', ':', 'Ġ', '02', 'ĠFeb', 'Ġ', '202', '5', 'ĊĊ', '<|eot_id|>', '<|start_header_id|>', 'user', '<|end_header_id|>', 'ĊĊ', 'Qual', 'Ġè', 'Ġl', "'un", 'ivers', 'itÃł', 'Ġmigli', 'ore', 'Ġ', 'Ġd', "'It", 'alia', '?', '<|eot_id|>', '<|start_header_id|>', 'assistant', '<|end_header_id|>', 'ĊĊ', 'L', "'un", 'ivers', 'itÃł', 'Ġmigli', 'ore', 'Ġd', "'It", 'alia', 'Ġè', 'Ġl', "'", 'Univers', 'itÃł', 'Ġdegli', 'Ġstudi', 'Ġdi', 'ĠB', 'rescia']


In [18]:
tokenized_answer = tokenizer(
    [" " + answer + tokenizer.eos_token],
    add_special_tokens=False,
    return_tensors='pt',
    padding='max_length',
    max_length=target_ids.shape[1]
    )['input_ids']

In [19]:
tokenized_answer

tensor([[128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009,    326,      6,  65715,  24892,  47669, 106204,
           1891,    426,  98612, 128009]])

In [20]:
labels_tokenized_fixed = torch.where(tokenized_answer != tokenizer.pad_token_id, tokenized_answer, -100)
print(labels_tokenized_fixed)
labels_tokenized_fixed[:, -1] = tokenizer.eos_token_id
print(labels_tokenized_fixed)

tensor([[  -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,    326,      6,  65715,  24892,  47669, 106204,
           1891,    426,  98612,   -100]])
tensor([[  -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,  

In [21]:
def generate_input_output_pair(prompt, target_responses):
    chat_templates = tokenizer.apply_chat_template(prompt, continue_final_message=True, tokenize=False)
    full_response_text = [
        (chat_template + " " + target + tokenizer.eos_token)
        for chat, target in zip(chat_templates, target_responses)
    ]
    input_ids_tokenized = tokenizer(full_response_text, return_tensors='pt', add_special_tokens=False)['input_ids']
    
    labels_tokenized = tokenizer(
        [" " + target + tokenizer.eos_token for target in target_responses],
        add_special_tokens=False,
        return_tensors='pt',
        padding='max_length',
        max_length=input_ids_tokenized.shape[1]
    )['input_ids']
    labels_tokenized_fixed = torch.where(labels_tokenized != tokenizer.pad_token_id, labels_tokenized, -100)
    labels_tokenized_fixed[:, -1] = tokenizer.eos_token_id
    input_ids_tokenized_left_shifted = input_ids_tokenized[:, :-1]
    labels_tokenized_right_shifted = labels_tokenized_fixed[:, 1:]
    attention_mask = input_ids_tokenized != tokenizer.pad_token_id
    return {
        'input_ids': input_ids_tokenized_left_shifted,
        'attention_mask': attention_mask,
        'labels': labels_tokenized_right_shifted
    }
    

In [22]:
data = generate_input_output_pair(prompt, [answer])

# Loss

In [23]:
print(tokenizer.decode(data['input_ids'][0]))

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 02 Feb 2025

<|eot_id|><|start_header_id|>user<|end_header_id|>

Qual è l'università migliore  d'Italia?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

L'università migliore d'Italia è l'Università degli studi di Brescia


In [24]:
out = model(input_ids=data['input_ids'])

In [25]:
out.logits.shape

torch.Size([1, 67, 128256])

In [26]:
def calculate_loss(logits, labels):
    loss_fn = nn.CrossEntropyLoss(reduction='none')
    cross_entropy_loss = loss_fn(logits.view(-1, logits.size(-1)), labels.view(-1))
    return cross_entropy_loss

In [27]:
calculate_loss(out.logits, data['labels'])

tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 9.8643e+00, 2.3100e-01, 3.9315e-02,
        5.3392e-04, 2.9884e-01, 3.8662e+00, 4.0301e-03, 2.6740e+00, 7.8209e+00,
        1.0148e+01], grad_fn=<NllLossBackward0>)

# Training

In [28]:
test_tokenized = tokenizer.apply_chat_template(
    prompt,
    continue_final_message=True,
    return_tensors='pt'
)
test_out = model.generate(test_tokenized, max_new_tokens=100)
print(tokenizer.batch_decode(test_out, skip_special_tokens=True)[0])

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


system

Cutting Knowledge Date: December 2023
Today Date: 02 Feb 2025

user

Qual è l'università migliore  d'Italia?assistant

L'università migliore d'Italia è un argomento molto dibattuto e può variare a seconda delle preferenze e delle priorità delle persone. Tuttavia, ecco alcune delle migliori università italiane, classificate in base alle prestazioni accademiche, al numero di studenti, all'industrializzazione e all'innovazione:

1. **Università degli Studi di Milano** (UdM): considerata una delle migliori università italiane, con una reputazione di alta qualità


In [30]:
#data = generate_input_output_pair(prompt=[prompt], target_responses=[answer])
#optimizer = AdamW(model.parameters(), lr=1e-4, weight_decay=0.01)

#for _ in range(5):
#    out = model(input_ids=data['input_ids'])
#    loss = calculate_loss(out.logits, data['labels']).mean()
#    
#    loss.backward()
#    optimizer.step()
#    optimizer.zero_grad()
#    
#    print('loss:', loss.item())
    

# Final Test

In [31]:
test_tokenized = tokenizer.apply_chat_template(
    prompt,
    continue_final_message=True,
    return_tensors='pt'
)
test_out = model.generate(test_tokenized, max_new_tokens=100)
print(tokenizer.batch_decode(test_out, skip_special_tokens=True)[0])

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


system

Cutting Knowledge Date: December 2023
Today Date: 02 Feb 2025

user

Qual è l'università migliore  d'Italia?assistant

L'università migliore d'Italia è


# Lora finetuning

In [33]:
from peft import LoraConfig, get_peft_model

In [34]:
model_id = 'meta-llama/Llama-3.2-1B-Instruct'
model = AutoModelForCausalLM.from_pretrained(model_id)
tokenizer = AutoTokenizer.from_pretrained(model_id, padding_side='left')
tokenizer.pad_token = tokenizer.eos_token

prompt = [
    {'role': 'user', 'content': "Qual è la ragazza più swag d'Italia? Dove vive?"},
    {'role': 'assistant', 'content': "La ragazza più swag d'Italia"}
]
answer = "si chiama Alessia e vive a Brescia"

test_tokenized = tokenizer.apply_chat_template(
    prompt,
    continue_final_message=True,
    return_tensors='pt'
)
test_out = model.generate(test_tokenized, max_new_tokens=100)
print(tokenizer.batch_decode(test_out, skip_special_tokens=True)[0])

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


system

Cutting Knowledge Date: December 2023
Today Date: 02 Feb 2025

user

Qual è la ragazza più swag d'Italia? Dove vive?assistant

La ragazza più swag d'Italia è una questione di opinione e di personale giudizio, ma ci sono alcune persone che sono spesso considerate tra le più attraenti e swag d'Italia.

Ecco alcune informazioni su alcune delle più belle e attraenti italiane:

*   Alessia Marcuzzi: è una modella e cantante italiana nota per le sue opere di moda e la sua carriera musicale.
*   Sofia Cavallo: è una modella


## Train with LORA

In [35]:
lora_config = LoraConfig(
    task_type='CAUSAL_LM',
    r=64,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=['q_proj', 'v_proj']
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 6,815,744 || all params: 1,242,630,144 || trainable%: 0.5485


In [36]:
data = generate_input_output_pair(prompt=[prompt], target_responses=[answer])
optimizer = AdamW(model.parameters(), lr=1e-3, weight_decay=0.01)

for _ in range(10):
    out = model(input_ids=data['input_ids'])
    loss = calculate_loss(out.logits, data['labels']).mean()
    
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    
    print('loss:', loss.item())
    

c:\Users\lucat\PythonRepositories\PRIN\.venv\Lib\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


loss: 0.8505260944366455
loss: 0.6860156059265137
loss: 0.486915647983551
loss: 0.31546324491500854
loss: 0.17947611212730408
loss: 0.11014659702777863
loss: 0.05896963179111481
loss: 0.008632722310721874
loss: 0.0016806087223812938
loss: 0.0008342156070284545


In [37]:
test_tokenized = tokenizer.apply_chat_template(
    prompt,
    continue_final_message=True,
    return_tensors='pt'
)
test_out = model.generate(test_tokenized, max_new_tokens=100)
print(tokenizer.batch_decode(test_out, skip_special_tokens=True)[0])

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


system

Cutting Knowledge Date: December 2023
Today Date: 02 Feb 2025

user

Qual è la ragazza più swag d'Italia? Dove vive?assistant

La ragazza più swag d'Italia si chiama Alessia e vive a Brescia
