In [1]:
import sys
import os
from dotenv import load_dotenv
from pathlib import Path

# if notebook is in PRIN/notebooks, parent() is PRIN
#project_root = Path.cwd().resolve().parent
#sys.path.insert(0, str(project_root))
#print("Added to sys.path:", project_root)

import json
from constants import Annotations, AnnotatedReport
import time
from IPython.display import clear_output

from huggingface_hub import login

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

from transformers import AutoTokenizer, DefaultDataCollator
from datasets import load_dataset, Dataset, DatasetDict


from classifiers import SimpleExtractor
from tqdm import tqdm
from sklearn.metrics import accuracy_score
import numpy as np

In [2]:
print(f'{torch.cuda.is_available() = }')  # True se la GPU è disponibile
print(f'{torch.cuda.device_count() = }')  # Numero di GPU disponibili
print(f'{torch.cuda.get_device_name(0) = }')  # Nome della GPU

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f'{device = }')

torch.cuda.is_available() = True
torch.cuda.device_count() = 1
torch.cuda.get_device_name(0) = 'NVIDIA GeForce GTX 1060 6GB'
device = device(type='cuda')


# BCEWithLogitsLoss

In [34]:
target = torch.tensor([[1, 0, 1]], dtype=float)  # 3 classes, batch size = 2
print(target)

tensor([[1., 0., 1.]], dtype=torch.float64)


In [35]:
output = torch.tensor([[2, -1, 0]], dtype=float)  # A prediction (logit)
print(output)

tensor([[ 2., -1.,  0.]], dtype=torch.float64)


In [49]:
criterion = torch.nn.BCEWithLogitsLoss()
bceloss = torch.nn.BCELoss()

In [37]:
criterion(output, target)  # -log(sigmoid(1.5))

tensor(0.3778, dtype=torch.float64)

In [38]:
nn.functional.sigmoid(output)

tensor([[0.8808, 0.2689, 0.5000]], dtype=torch.float64)

In [50]:
bceloss(nn.functional.sigmoid(output), target)

tensor(0.3778, dtype=torch.float64)

In [43]:
- 2 + np.log(1 + np.exp(2))

np.float64(0.1269280110429727)

In [45]:
np.log(1 + np.exp(0))

np.float64(0.6931471805599453)

In [46]:
np.log(1 + np.exp(-1))

np.float64(0.31326168751822286)

In [48]:
(0.31 + 0.69 + 0.12) / 3

0.37333333333333335