In [5]:
import sys
import os
from dotenv import load_dotenv
from pathlib import Path

# if notebook is in PRIN/notebooks, parent() is PRIN
#project_root = Path.cwd().resolve().parent
#sys.path.insert(0, str(project_root))
#print("Added to sys.path:", project_root)

import json
from constants import Annotations, AnnotatedReport
import time
from IPython.display import clear_output

from huggingface_hub import login

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

from transformers import AutoTokenizer, DefaultDataCollator
from datasets import load_dataset, Dataset, DatasetDict


from tqdm import tqdm
from sklearn.metrics import accuracy_score
import numpy as np

In [ ]:
print(f'{torch.cuda.is_available() = }')  # True se la GPU è disponibile
print(f'{torch.cuda.device_count() = }')  # Numero di GPU disponibili
print(f'{torch.cuda.get_device_name(0) = }')  # Nome della GPU

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f'{device = }')

torch.cuda.is_available() = True
torch.cuda.device_count() = 1
torch.cuda.get_device_name(0) = 'NVIDIA GeForce RTX 5070'
device = device(type='cuda')


In [17]:
y = torch.tensor(
    [[0],
     [1],
     [1]],
dtype=torch.float32)

x = torch.tensor(
    [[3],
     [10],
     [-5]],
dtype=torch.float32)

In [18]:
y.squeeze(-1)

tensor([0., 1., 1.])

In [21]:
torch.nn.functional.binary_cross_entropy_with_logits(x, y)

tensor(2.6851)

In [47]:
lista = []

In [48]:
lista.extend((nn.functional.sigmoid(x) > 0.5).int().squeeze(-1).cpu().numpy())

In [49]:
lista

[np.int32(1), np.int32(1), np.int32(0)]

In [37]:
(-np.log(1-0.9526) - np.log(0.0067))/3

np.float64(2.6849269342887747)

In [39]:
torch.nn.functional.mse_loss(x.squeeze(-1), y)

C:\Users\lucat\AppData\Local\Temp\ipykernel_7448\3223416801.py:1: UserWarning: Using a target size (torch.Size([3, 1])) that is different to the input size (torch.Size([3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  torch.nn.functional.mse_loss(x.squeeze(-1), y)


tensor(41.7778)

In [25]:
((x-y)**2).mean()

tensor(42.)

In [69]:
(x > 0).int()

tensor([[1, 1, 0],
        [0, 1, 0]], dtype=torch.int32)

In [70]:
(x > 0).int().cpu().numpy()

array([[1, 1, 0],
       [0, 1, 0]], dtype=int32)

In [71]:
y.extend((x > 0).int().cpu().numpy())

In [72]:
y

[array([1, 1, 0], dtype=int32), array([0, 1, 0], dtype=int32)]

# BCEWithLogitsLoss

In [34]:
target = torch.tensor([[1, 0, 1]], dtype=float)  # 3 classes, batch size = 2
print(target)

tensor([[1., 0., 1.]], dtype=torch.float64)


In [35]:
output = torch.tensor([[2, -1, 0]], dtype=float)  # A prediction (logit)
print(output)

tensor([[ 2., -1.,  0.]], dtype=torch.float64)


In [49]:
criterion = torch.nn.BCEWithLogitsLoss()
bceloss = torch.nn.BCELoss()

In [37]:
criterion(output, target)  # -log(sigmoid(1.5))

tensor(0.3778, dtype=torch.float64)

In [38]:
nn.functional.sigmoid(output)

tensor([[0.8808, 0.2689, 0.5000]], dtype=torch.float64)

In [50]:
bceloss(nn.functional.sigmoid(output), target)

tensor(0.3778, dtype=torch.float64)

In [43]:
- 2 + np.log(1 + np.exp(2))

np.float64(0.1269280110429727)

In [45]:
np.log(1 + np.exp(0))

np.float64(0.6931471805599453)

In [46]:
np.log(1 + np.exp(-1))

np.float64(0.31326168751822286)

In [48]:
(0.31 + 0.69 + 0.12) / 3

0.37333333333333335

In [7]:
a = [torch.tensor(1), torch.tensor(2), torch.tensor(3)]

In [8]:
sum(a) / len(a)

tensor(2.)

In [9]:
torch.sum(a)

TypeError: sum(): argument 'input' (position 1) must be Tensor, not list