In [2]:
from transformers import AutoModelForCausalLM, AutoTokenizer, AdamW
from transformers import pipeline


import torch

from huggingface_hub import notebook_login, login

from pprint import pprint

import torch.nn as nn

token = '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' 

#device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = torch.device('cpu')
print(f'Using device: {device}')

login(token=token)

Using device: cpu


In [2]:
model_id = 'meta-llama/Llama-3.2-1B-Instruct'
model = AutoModelForCausalLM.from_pretrained(model_id)
tokenizer = AutoTokenizer.from_pretrained(model_id, padding_side='left')

generation_pipeline = pipeline('text-generation', model=model, tokenizer=tokenizer, device=device)

Device set to use cpu


# Examples

In [3]:
generation_pipeline('The capital of Italy is', max_new_tokens=150)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


[{'generated_text': "The capital of Italy is Rome. Rome is a major city in Italy known for its rich history, architecture, and art. The city is home to many famous landmarks such as the Colosseum, the Pantheon, and the Vatican City. Rome is also known for its delicious food and wine. Visitors to Rome often spend their days exploring the city's many historical sites and enjoying the local cuisine. The city has a population of over 2.8 million people and is a popular destination for tourists from all over the world."}]

In [4]:
prompt = [
    "The capital of Italy is",
    'Hello, my name is Luca and I am a software'
]

tokenizer.pad_token = tokenizer.eos_token

tokenized = tokenizer(prompt, return_tensors='pt', padding=True).to(device)
pprint(tokenized)

tokenizer.batch_decode(tokenized['input_ids'])

generation_pipeline(prompt, max_new_tokens=50)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


{'attention_mask': tensor([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]),
 'input_ids': tensor([[128009, 128009, 128009, 128009, 128009, 128009, 128000,    791,   6864,
            315,  15704,    374],
        [128000,   9906,     11,    856,    836,    374,  84278,    323,    358,
           1097,    264,   3241]])}


Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


[[{'generated_text': 'The capital of Italy is Rome.\nThe capital of Italy is Rome.\nThe capital of Italy is Rome.\nThe capital of Italy is Rome.\nThe capital of Italy is Rome.\nThe capital of Italy is Rome.\nThe capital of Italy is Rome.\nThe capital of Italy is Rome'}],
 [{'generated_text': "Hello, my name is Luca and I am a software engineer with a passion for coding. I've been working on a project to build a chatbot that can understand and respond to user queries. I've been using Python as my primary language for this project and I've been experimenting with different libraries and frameworks"}]]

In [5]:
prompt =[
    {
        'role': 'system',
        'content': 'Tu sei un medico'
    },
    {
        'role': 'user',
        'content': 'Scrivi un referto di una risonanza magnetica per un paziente con sospetto caso di tumore al colon retto'
    }
]

In [6]:
tokenized = tokenizer.apply_chat_template(
    prompt,
    add_gneration_prompt=True,
    tokenize=False,
    padding=True,
    return_tensors='pt'
)

pprint(tokenized)

('<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n'
 '\n'
 'Cutting Knowledge Date: December 2023\n'
 'Today Date: 10 Feb 2025\n'
 '\n'
 'Tu sei un medico<|eot_id|><|start_header_id|>user<|end_header_id|>\n'
 '\n'
 'Scrivi un referto di una risonanza magnetica per un paziente con sospetto '
 'caso di tumore al colon retto<|eot_id|>')


In [7]:
tokenized = tokenizer.apply_chat_template(
    prompt,
    add_gneration_prompt=True,
    tokenize=True,
    padding=True,
    return_tensors='pt'
)

pprint(tokenized)

tensor([[128000, 128006,   9125, 128007,    271,  38766,   1303,  33025,   2696,
             25,   6790,    220,   2366,     18,    198,  15724,   2696,     25,
            220,    605,  13806,    220,   2366,     20,    271,  54071,  43237,
            653,   1812,   4042, 128009, 128006,    882, 128007,    271,  66608,
          33920,    653,   2098,  14200,   1891,   5203,    436,   3416,  27564,
          33297,   3074,    824,    653,  80585,  13140,    390,    274,   4890,
          53979,  23884,   1891,  15756,    461,    453,  15235,   2160,    998,
         128009]])


In [8]:
output = model.generate(tokenized, max_new_tokens=100)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


In [9]:
pprint(tokenizer.batch_decode(output))

['<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n'
 '\n'
 'Cutting Knowledge Date: December 2023\n'
 'Today Date: 10 Feb 2025\n'
 '\n'
 'Tu sei un medico<|eot_id|><|start_header_id|>user<|end_header_id|>\n'
 '\n'
 'Scrivi un referto di una risonanza magnetica per un paziente con sospetto '
 'caso di tumore al colon '
 'retto<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n'
 '\n'
 '**Confidenza medica**\n'
 '\n'
 '**Data:** 10 Febbraio 2025\n'
 '\n'
 '**Nome e cognome:** \\[Nome del paziente]\n'
 '\n'
 '**Indirizzo:** \\[Indirizzo del paziente]\n'
 '\n'
 '**Città e stato:** \\[Città e stato del paziente]\n'
 '\n'
 '**Ora:** \\[Ora del test]\n'
 '\n'
 '**Teste medico:** \\[Nome e cognome del medico]\n'
 '\n'
 '**Descrizione del']


In [10]:
prompt =[
    {
        'role': 'system',
        'content': 'Tu sei un medico'
    },
    {
        'role': 'user',
        'content': 'Scrivi un referto di una risonanza magnetica per un paziente con sospetto caso di tumore al colon retto'
    },
    {
        'role': 'assistant',
        'content': "Si documenta la presenza di un'ispessimento circonferenziale delle pareti della retto medio, con "
    }
]

#Remove the generation prompt
tokenized = tokenizer.apply_chat_template(
    prompt,
    add_gneration_prompt=False,
    continue_final_message=True,
    tokenize=True,
    padding=True,
    return_tensors='pt'
)
output = model.generate(tokenized, max_new_tokens=200)
pprint(tokenizer.batch_decode(output))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


['<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n'
 '\n'
 'Cutting Knowledge Date: December 2023\n'
 'Today Date: 10 Feb 2025\n'
 '\n'
 'Tu sei un medico<|eot_id|><|start_header_id|>user<|end_header_id|>\n'
 '\n'
 'Scrivi un referto di una risonanza magnetica per un paziente con sospetto '
 'caso di tumore al colon '
 'retto<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n'
 '\n'
 "Si documenta la presenza di un'ispessimento circonferenziale delle pareti "
 "della retto medio, con un'area di iperlatticazione centrale, evidenziata "
 "dalla segnatura di un'espansione anormale.\n"
 '\n'
 'La risonanza magnetica (MRI) effettuata il 15/02/2023, evidenziata con '
 "un'immagine T1-weighted, mostra una presenza di un'area iperlattica con una "
 'dimensione di 4,5 cm x 3,8 cm, localizzata nella parte inferiore della '
 'colonna rettale, con una dimensione di 3,2 cm x 2,8 cm.\n'
 '\n'
 "La segnatura di un'espansione anormale è evidenziata dalla segnatura di "
 "un'espansio

# Training

In [13]:
prompt = [
    {'role': 'user', 'content': "Qual è l'università migliore  d'Italia?"},
    {'role': 'assistant', 'content': "L'università migliore d'Italia è"}
]
answer = "l'Università degli studi di Brescia"

In [14]:
chat_template = tokenizer.apply_chat_template(
    prompt,
    continue_final_message=True,
    tokenize=False
)
#print(chat_template)

In [15]:
full_response_text = chat_template + " " + answer + tokenizer.eos_token
#print(full_response_text)

In [17]:
full_response_text_tokenized = tokenizer(
    full_response_text,
    return_tensors='pt',
    add_special_tokens=False
)['input_ids']
#full_response_text_tokenized

In [18]:
input_ids = full_response_text_tokenized[:, :-1]
target_ids = full_response_text_tokenized[:, 1:]
#print(input_ids)
#print(target_ids)

In [19]:
#print(tokenizer.convert_ids_to_tokens(input_ids[0]))

In [20]:
tokenized_answer = tokenizer(
    [" " + answer + tokenizer.eos_token],
    add_special_tokens=False,
    return_tensors='pt',
    padding='max_length',
    max_length=target_ids.shape[1]
    )['input_ids']

In [21]:
tokenized_answer

tensor([[128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009,    326,      6,  65715,  24892,  47669, 106204,
           1891,    426,  98612, 128009]])

In [22]:
labels_tokenized_fixed = torch.where(tokenized_answer != tokenizer.pad_token_id, tokenized_answer, -100)
print(labels_tokenized_fixed)
labels_tokenized_fixed[:, -1] = tokenizer.eos_token_id
print(labels_tokenized_fixed)

tensor([[  -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,    326,      6,  65715,  24892,  47669, 106204,
           1891,    426,  98612,   -100]])
tensor([[  -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,  

# Carica referti

In [8]:
import pandas as pd

model_id = 'meta-llama/Llama-3.2-1B-Instruct'
model = AutoModelForCausalLM.from_pretrained(model_id)
tokenizer = AutoTokenizer.from_pretrained(model_id, padding_side='left')
tokenizer.pad_token = tokenizer.eos_token

data_path = 'C:\\Users\\lucat\\OneDrive\\TESI_MAGISTRALE\\Referti\Referti non strutturati retto\\Referti con annotazioni.xlsx'
data = pd.read_excel(data_path, index_col=0)
data = data.T
#narratives = data.iloc[:, 2]
pprint(data.columns)

Index(['Intestazione', 'Esame', 'TESTO:', 'TECNICA:',
       'QUALITA' DELLE IMMAGINI: ', 'INDICAZIONI: ', 'CONFRONTO: ', 'RETTO:',
       'Posizione: ', 'Estensione cranio-caudale: ',
       'Estensione circonferenziale: ', 'Infiltrazione sfintere: ',
       'Coinvolgimento fascia mesorettale:',
       'Localizzazione della distanza minima tra tumore e MRF (mesorectal fascia): ',
       'Linfonodi mesorettali: ', 'Depositi tumorali: ', 'Altri reperti: ',
       'CONCLUSIONI: ',
       'Note cliniche GEMELLI: mi piacerebbe conoscere lo stato EMVI (extramural vascular invasion), se ci sono linfonodi extra mesorettali positivi (inguinali, otturatori, iliaci interni ed esterni, iliaci comuni)'],
      dtype='object', name='Caso')


In [9]:
# Select Narratives (testo dei referti)
narratives = data['TESTO:']
narratives.reset_index(drop=True, inplace=True)
data = pd.DataFrame(narratives)
data.rename(columns={'TESTO:': 'Testo'}, inplace=True)
print(data)

                                               Testo
0  Esame eseguito secondo piani multipli, mediant...
1  L'esame è stato eseguito mediante sequenze HAS...
2  Motivo dell'esame: neoformazione del retto. L'...
3  Indagine eseguita mediante sequenze T2 e T1-di...
4  L'esame è stato eseguito mediante sequenze FSE...
5  Tecnica: sequenze FSE, DWI, FSPGR 3D-DISCO pri...
6  L'esame è srtato eseguito medinte sequenze FSE...
7  Esame eseguito mediante sequenze FSE,GRE e DWI...
8  L'esame è stato eseguito mediante sequenze FSE...
9  L'esame è stato eseguito mediante sequenze FSE...


# Genera prompt per allenamento

In [10]:
basic_prompt =[
    {
        'role': 'system',
        'content': 'Tu sei un medico'
    },
    {
        'role': 'user',
        'content': 'Scrivi un referto di una risonanza magnetica per un paziente con sospetto caso di tumore al colon retto'
    },
    {
        'role': 'assistant',
        'content': ""
    }
]

prompts = []
for text in data['Testo']:
    prompts.append(basic_prompt)
    
target_responses = data['Testo'].to_list()

In [11]:
def generate_input_output_pair(prompts, target_responses):
    chat_templates = tokenizer.apply_chat_template(prompts, continue_final_message=True, tokenize=False)
    full_response_text = [
        #(chat + " " + target + tokenizer.eos_token)
        (chat + target + tokenizer.eos_token)
        for chat, target in zip(chat_templates, target_responses)
    ]
    input_ids_tokenized = tokenizer(full_response_text, return_tensors='pt', add_special_tokens=False, padding=True)['input_ids']
    
    labels_tokenized = tokenizer(
        [" " + target + tokenizer.eos_token for target in target_responses],
        add_special_tokens=False,
        return_tensors='pt',
        padding='max_length',
        max_length=input_ids_tokenized.shape[1]
    )['input_ids']
    labels_tokenized_fixed = torch.where(labels_tokenized != tokenizer.pad_token_id, labels_tokenized, -100)
    labels_tokenized_fixed[:, -1] = tokenizer.eos_token_id
    input_ids_tokenized_left_shifted = input_ids_tokenized[:, :-1]
    labels_tokenized_right_shifted = labels_tokenized_fixed[:, 1:]
    attention_mask = input_ids_tokenized != tokenizer.pad_token_id
    return {
        'input_ids': input_ids_tokenized_left_shifted,
        'attention_mask': attention_mask,
        'labels': labels_tokenized_right_shifted
    }
    

In [12]:

data = generate_input_output_pair(prompts, target_responses)
print(data['input_ids'])
print(data['attention_mask'])
print(data['labels'])

tensor([[128009, 128009, 128009,  ...,   7546,   8115,    570],
        [128009, 128009, 128009,  ...,    328,     17,     13],
        [128009, 128009, 128009,  ...,    992,     72,     13],
        ...,
        [128000, 128006,   9125,  ...,   5683,   1604,     13],
        [128009, 128009, 128009,  ...,   1891,   4224,     13],
        [128009, 128009, 128009,  ...,     18,    452,     16]])
tensor([[False, False, False,  ...,  True,  True, False],
        [False, False, False,  ...,  True,  True, False],
        [False, False, False,  ...,  True,  True, False],
        ...,
        [ True,  True,  True,  ...,  True,  True, False],
        [False, False, False,  ...,  True,  True, False],
        [False, False, False,  ...,  True,  True, False]])
tensor([[  -100,   -100,   -100,  ...,   8115,    570, 128009],
        [  -100,   -100,   -100,  ...,     17,     13, 128009],
        [  -100,   -100,   -100,  ...,     72,     13, 128009],
        ...,
        [  -100,   -100,   -100,  .

# Loss

In [13]:
print(tokenizer.decode(data['input_ids'][0]))

<|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|><|eot_id|>

In [88]:
out = model(input_ids=data['input_ids'])

In [89]:
out.logits.shape

torch.Size([10, 660, 128256])

In [19]:
def calculate_loss(logits, labels):
    loss_fn = nn.CrossEntropyLoss(reduction='none')
    cross_entropy_loss = loss_fn(logits.view(-1, logits.size(-1)), labels.view(-1))
    return cross_entropy_loss

In [ ]:
#calculate_loss(out.logits, data['labels'])

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

# Training

In [14]:
test_tokenized = tokenizer.apply_chat_template(
    prompts,
    continue_final_message=True,
    return_tensors='pt'
)
test_out = model.generate(test_tokenized, max_new_tokens=100)
print(tokenizer.batch_decode(test_out, skip_special_tokens=True)[0])

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


system

Cutting Knowledge Date: December 2023
Today Date: 10 Feb 2025

Tu sei un medicouser

Scrivi un referto di una risonanza magnetica per un paziente con sospetto caso di tumore al colon rettoassistant

assistant

**REFERTO RISONANZA MAGNETICA**

**Data:** \[Data dell'esame]

**Patient:** \[Nome e cognome del paziente, in questo caso "Paziente A"]

**Indicazione terapeutica:** Risonanza magnetica pervalore

**Sintesi del caso:**

Il paziente A, \[nome e cognome], \[età], \[indirizzo], \[numero


In [30]:
#data = generate_input_output_pair(prompt=[prompt], target_responses=[answer])
#optimizer = AdamW(model.parameters(), lr=1e-4, weight_decay=0.01)

#for _ in range(5):
#    out = model(input_ids=data['input_ids'])
#    loss = calculate_loss(out.logits, data['labels']).mean()
#    
#    loss.backward()
#    optimizer.step()
#    optimizer.zero_grad()
#    
#    print('loss:', loss.item())
    

# Final Test

In [93]:
#test_tokenized = tokenizer.apply_chat_template(
#    prompts,
#    continue_final_message=True,
#    return_tensors='pt'
#)
#test_out = model.generate(test_tokenized, max_new_tokens=100)
#print(tokenizer.batch_decode(test_out, skip_special_tokens=True)[0])

# Lora finetuning

In [15]:
from peft import LoraConfig, get_peft_model

In [16]:
model_id = 'meta-llama/Llama-3.2-1B-Instruct'
model = AutoModelForCausalLM.from_pretrained(model_id)
tokenizer = AutoTokenizer.from_pretrained(model_id, padding_side='left')
tokenizer.pad_token = tokenizer.eos_token


test_tokenized = tokenizer.apply_chat_template(
    prompts,
    continue_final_message=True,
    return_tensors='pt'
)
test_out = model.generate(test_tokenized, max_new_tokens=1000)
print(tokenizer.batch_decode(test_out, skip_special_tokens=True)[0])

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


system

Cutting Knowledge Date: December 2023
Today Date: 10 Feb 2025

Tu sei un medicouser

Scrivi un referto di una risonanza magnetica per un paziente con sospetto caso di tumore al colon rettoassistant

assistant

**Referto di Risonanza Magnetica**

**Data di esecuzione:** 10 Febbraio 2025

**Paziente:** \[Nome e cognome del paziente non fornito per motivi di privacy]

**Assunto:** Sospetto caso di tumore al colon retto

**Descrizione del paziente:**

- \[Nome e cognome del paziente]
- \[Età del paziente]
- \[Sexo del paziente]
- \[Stato di salute del paziente]
- \[Data di nascita del paziente]

**Simboli risonanza magnetica:**

- **Tabelle di risultati:**
  - Tabello 1: Tabelle dei risultati della risonanza magnetica del colon retto
  - Tabello 2: Tabelle dei risultati della risonanza magnetica della regione retrocelessale
- **Gruppi di contrasto:**
  - Gruppo A: Tabelle dei risultati della risonanza magnetica del colon retto
  - Gruppo B: Tabelle dei risultati della risonanza mag

## Train with LORA

In [17]:
lora_config = LoraConfig(
    task_type='CAUSAL_LM',
    r=64,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=['q_proj', 'v_proj']
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 6,815,744 || all params: 1,242,630,144 || trainable%: 0.5485


In [20]:
data = generate_input_output_pair(prompts, target_responses)
optimizer = AdamW(model.parameters(), lr=1e-3, weight_decay=0.01)

for _ in range(10):
    out = model(input_ids=data['input_ids'])
    loss = calculate_loss(out.logits, data['labels']).mean()
    
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    
    print('loss:', loss.item())
    

: 

In [37]:
test_tokenized = tokenizer.apply_chat_template(
    prompts,
    continue_final_message=True,
    return_tensors='pt'
)
test_out = model.generate(test_tokenized, max_new_tokens=100)
print(tokenizer.batch_decode(test_out, skip_special_tokens=True)[0])

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


system

Cutting Knowledge Date: December 2023
Today Date: 02 Feb 2025

user

Qual è la ragazza più swag d'Italia? Dove vive?assistant

La ragazza più swag d'Italia si chiama Alessia e vive a Brescia
